# Generated by Django 3.0.5 on 2020-04-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
    ]
