# Generated by Django 3.0.5 on 2020-04-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_remove_orders_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.AddField(
            model_name='destination',
            name='person',
            field=models.IntegerField(null=True),
        ),
    ]
