# Generated by Django 3.0.5 on 2020-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20200412_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='person',
        ),
        migrations.AlterField(
            model_name='order',
            name='totalOrderCost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
